site_name: Документация Скал@пендра
site_url: https://alptur.github.io/scaladocs
theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
